# If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: All things bright and beautiful

email: hi@ashang.org
  #For a moment, nothing happened. Then, after a second or so, nothing continued to happen.

description: > # this means to ignore newlines until "baseurl:"
  For a moment, nothing happened.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://ashang.org" # the base hostname & protocol for your site, e.g. http://example.com

github_username: ashang

# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:title

# gems:
#  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
 
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
# Start from https://lab.github.com/courses
